skip_tags: true
image: Visual Studio 2019 Preview
environment:  
  BENCHMARKS: on  

install:
  - cmd: choco install gitversion.portable -pre --version 4.0.1-beta1-65 -y
  #- ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: choco install dotnetcore-sdk --pre

before_build:
  - ps: gitversion /l console /output buildserver

build:
  verbosity: detailed
build_script:
- cmd: dotnet restore ./src/FileOnServerAuth.sln --disable-parallel
- cmd: dotnet build ./src/FileOnServerAuth.sln -c Release --disable-parallel
- cmd: dotnet pack ./src/FileOnServerAuth.sln -c Release --output %APPVEYOR_BUILD_FOLDER%/artifacts/
artifacts:
- path: artifacts/*
deploy:
  provider: NuGet
  api_key:
    secure: u8JpW5kkti8pMi+ra2QcXTJPhkHCA8pkKSiiZOJbcS/vFVHNvF3W8qw1Fy2If6a7
  skip_symbols: false
  artifact: /.*\.nupkg/